// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.REVLibError;
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class BallHandlingSystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private CANSparkMax loadMotor1;
private CANSparkMax loadMotor2;
private MotorControllerGroup loadMotors;
private CANSparkMax stagingMotor;
private CANSparkMax shootMotor;
private DigitalInput loadSensor;
private DigitalInput stagingSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public BallHandlingSystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
loadMotor1 = new CANSparkMax(4, MotorType.kBrushless);
 
 loadMotor1.restoreFactoryDefaults();  
loadMotor1.setInverted(false);
loadMotor1.setIdleMode(IdleMode.kCoast);
  

loadMotor2 = new CANSparkMax(9, MotorType.kBrushless);
 
 loadMotor2.restoreFactoryDefaults();  
loadMotor2.setInverted(false);
loadMotor2.setIdleMode(IdleMode.kCoast);
  

loadMotors = new MotorControllerGroup(loadMotor1, loadMotor2  );
 addChild("LoadMotors",loadMotors);
 

stagingMotor = new CANSparkMax(6, MotorType.kBrushless);
 
 stagingMotor.restoreFactoryDefaults();  
stagingMotor.setInverted(false);
stagingMotor.setIdleMode(IdleMode.kCoast);
  

shootMotor = new CANSparkMax(5, MotorType.kBrushless);
 
 shootMotor.restoreFactoryDefaults();  
shootMotor.setInverted(false);
shootMotor.setIdleMode(IdleMode.kCoast);
  

loadSensor = new DigitalInput(0);
 addChild("LoadSensor", loadSensor);
 

stagingSensor = new DigitalInput(1);
 addChild("StagingSensor", stagingSensor);
 


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

